In [1]:
import keras

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [7]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD,Adagrad, Adadelta, Adam

In [8]:
# generating the dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

In [9]:
x_train

array([[0.86108228, 0.99524268, 0.274512  , ..., 0.53731849, 0.82773079,
        0.68980885],
       [0.25088614, 0.93150421, 0.22172361, ..., 0.36482609, 0.22475562,
        0.72125103],
       [0.31073636, 0.65718982, 0.71561134, ..., 0.84644215, 0.22985518,
        0.18679091],
       ...,
       [0.74764249, 0.80803105, 0.66112106, ..., 0.62115948, 0.11954591,
        0.8350158 ],
       [0.97361005, 0.32484802, 0.39129604, ..., 0.55764411, 0.94607136,
        0.3476408 ],
       [0.24747932, 0.90575282, 0.75183311, ..., 0.39454875, 0.70398393,
        0.22315992]])

In [10]:
model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

In [11]:
model.fit(x_train,y_train, epochs = 20, batch_size= 32)
score = model.evaluate(x_test, y_test, batch_size= 32)

Epoch 1/20
1000/1000 [==============================] - 0s 319us/step - loss: 2.3414 - acc: 0.1180
Epoch 2/20
1000/1000 [==============================] - 0s 81us/step - loss: 2.3272 - acc: 0.1130
Epoch 3/20
1000/1000 [==============================] - 0s 96us/step - loss: 2.3097 - acc: 0.1010
Epoch 4/20
1000/1000 [==============================] - 0s 103us/step - loss: 2.3115 - acc: 0.0910
Epoch 5/20
1000/1000 [==============================] - 0s 121us/step - loss: 2.3102 - acc: 0.1060
Epoch 6/20
1000/1000 [==============================] - 0s 125us/step - loss: 2.3001 - acc: 0.1050
Epoch 7/20
1000/1000 [==============================] - 0s 103us/step - loss: 2.3073 - acc: 0.0920
Epoch 8/20
1000/1000 [==============================] - 0s 122us/step - loss: 2.2952 - acc: 0.1100
Epoch 9/20
1000/1000 [==============================] - 0s 91us/step - loss: 2.3012 - acc: 0.1200
Epoch 10/20
1000/1000 [==============================] - 0s 91us/step - loss: 2.2960 - acc: 0.1200
Epoch 11/20
1

In [12]:
print(score)

[2.317858352661133, 0.09]


# Binary Classification

In [27]:
import keras
import numpy as np

In [28]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD, Adam, Adadelta,adagrad, rmsprop

In [29]:
np.random.seed(123)
X_train = np.random.random((1000, 2))
Y_train = keras.utils.to_categorical(np.random.randint(2, size = (1000, 1)), num_classes= 2)
X_test = np.random.random((100,2))
Y_test = keras.utils.to_categorical(np.random.randint(2, size = (100, 1)), num_classes= 2)

In [30]:
model1 = Sequential()
model1.add(Dense(64, activation= 'relu', input_dim = 2))
model1.add(Dense(64, activation = 'relu'))
model1.add(Dense(2, activation='softmax'))

In [39]:
model1.compile(loss = 'binary_crossentropy', optimizer= 'rmsprop', metrics= ['accuracy'])

In [40]:
model1.fit(X_train,Y_train, epochs = 10, verbose= 1)

Epoch 1/10
1000/1000 [==============================] - 1s 512us/step - loss: 0.6905 - acc: 0.5300
Epoch 2/10
1000/1000 [==============================] - 0s 77us/step - loss: 0.6899 - acc: 0.5260
Epoch 3/10
1000/1000 [==============================] - 0s 71us/step - loss: 0.6907 - acc: 0.5290
Epoch 4/10
1000/1000 [==============================] - 0s 73us/step - loss: 0.6905 - acc: 0.5260
Epoch 5/10
1000/1000 [==============================] - 0s 83us/step - loss: 0.6904 - acc: 0.5290
Epoch 6/10
1000/1000 [==============================] - 0s 73us/step - loss: 0.6902 - acc: 0.5300
Epoch 7/10
1000/1000 [==============================] - 0s 66us/step - loss: 0.6906 - acc: 0.5210
Epoch 8/10
1000/1000 [==============================] - 0s 75us/step - loss: 0.6905 - acc: 0.5290
Epoch 9/10
1000/1000 [==============================] - 0s 74us/step - loss: 0.6899 - acc: 0.5250
Epoch 10/10
1000/1000 [==============================] - 0s 79us/step - loss: 0.6898 - acc: 0.5230


In [41]:
model1.evaluate(X_test, Y_test, batch_size= 128)

100/100 [==============================] - 0s 2ms/step


[0.7062636017799377, 0.4300000071525574]

# VGG-like convet

In [1]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD, Adadelta, Adam, adagrad, rmsprop

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# generate the dummy data 
x_train = np.random.random((100, 100, 100, 3))
y_train = keras.utils.to_categorical(np.random.randint(10, size = (100, 1)), num_classes= 10)
x_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(np.random.randint(10, size = (20,1)), num_classes= 10)

In [3]:
x_train.shape
print(x_train)

[[[[0.28270582 0.49160121 0.78219757]
   [0.19231449 0.9708901  0.21635187]
   [0.56205806 0.02597156 0.95553157]
   ...
   [0.04148871 0.63022408 0.3726149 ]
   [0.5841292  0.23282061 0.46006192]
   [0.32503608 0.10801225 0.79056636]]

  [[0.05638819 0.86679716 0.09489613]
   [0.45671117 0.22261168 0.32855956]
   [0.44064072 0.32465476 0.23934242]
   ...
   [0.45714279 0.19710152 0.50887989]
   [0.48184605 0.25062309 0.95409808]
   [0.03018942 0.38752317 0.85901128]]

  [[0.35820392 0.59808167 0.22935239]
   [0.77740446 0.66984558 0.27060891]
   [0.96167175 0.40559523 0.65732775]
   ...
   [0.76733118 0.34125094 0.47367428]
   [0.80915117 0.46411051 0.77072145]
   [0.35712915 0.51922134 0.14712915]]

  ...

  [[0.10741721 0.67444663 0.22935828]
   [0.27348752 0.43166481 0.32012881]
   [0.96578425 0.59754255 0.50533862]
   ...
   [0.0118613  0.45469186 0.07782329]
   [0.62187185 0.63765389 0.05394874]
   [0.77022106 0.685339   0.05435114]]

  [[0.63685465 0.64405749 0.62578472]
   [0.6

In [4]:
model = Sequential()
# input: 100x100 images with 3 channels -> (100, 100, 3) tensors.
# this applies 32 convolution filters of size 3x3 each.
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.001, decay=1e-6, momentum=0.1, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer= 'rmsprop', metrics= ['accuracy'])


In [5]:
model.fit(x_train, y_train, batch_size= 32, epochs= 10)

Epoch 1/10
100/100 [==============================] - 6s 61ms/step - loss: 5.9654 - acc: 0.1100
Epoch 2/10
100/100 [==============================] - 5s 54ms/step - loss: 2.2977 - acc: 0.1300
Epoch 3/10
100/100 [==============================] - 5s 53ms/step - loss: 2.3796 - acc: 0.0800
Epoch 4/10
100/100 [==============================] - 5s 50ms/step - loss: 2.3027 - acc: 0.1100
Epoch 5/10
100/100 [==============================] - 5s 50ms/step - loss: 2.2987 - acc: 0.0800
Epoch 6/10
100/100 [==============================] - 5s 52ms/step - loss: 2.2990 - acc: 0.1500
Epoch 7/10
100/100 [==============================] - 5s 53ms/step - loss: 2.2996 - acc: 0.0700
Epoch 8/10
100/100 [==============================] - 5s 53ms/step - loss: 2.2984 - acc: 0.1000
Epoch 9/10
100/100 [==============================] - 5s 52ms/step - loss: 2.2982 - acc: 0.1000
Epoch 10/10
100/100 [==============================] - 6s 57ms/step - loss: 2.2971 - acc: 0.1200


In [59]:
score = model.evaluate(x_test, y_test, batch_size=32)
score

20/20 [==============================] - 0s 18ms/step


[2.3695788383483887, 0.05000000074505806]

Sequence classification with LSTM

In [8]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
import numpy as np

In [9]:
data_dim = 16
timesteps = 8
num_classes = 10

In [12]:
model = Sequential()
model.add(LSTM(32, return_sequences= True,
              input_shape = (timesteps, data_dim)))
model.add(LSTM(32, return_sequences= True))
model.add(LSTM(32))
model.add(Dense(10, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer= 'Adam', metrics= ['accuracy'])

In [17]:
X_train = np.random.random((1000, timesteps, data_dim))
Y_train = np.random.random((1000, num_classes))

In [18]:
X_val = np.random.random((1000, timesteps, data_dim))
Y_val = np.random.random((1000, num_classes))

In [19]:
model.fit(X_train, Y_train, verbose= 1, epochs= 10, batch_size= 32, validation_data= (X_val, Y_val))

Train on 1000 samples, validate on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 3s 3ms/step - loss: 11.5072 - acc: 0.0940 - val_loss: 11.5801 - val_acc: 0.0880
Epoch 2/10
1000/1000 [==============================] - 1s 728us/step - loss: 11.5052 - acc: 0.0870 - val_loss: 11.5806 - val_acc: 0.1130
Epoch 3/10
1000/1000 [==============================] - 1s 731us/step - loss: 11.5052 - acc: 0.1030 - val_loss: 11.5790 - val_acc: 0.1150
Epoch 4/10
1000/1000 [==============================] - 1s 746us/step - loss: 11.5046 - acc: 0.1040 - val_loss: 11.5814 - val_acc: 0.0910
Epoch 5/10
1000/1000 [==============================] - 1s 769us/step - loss: 11.5041 - acc: 0.0980 - val_loss: 11.5796 - val_acc: 0.1070
Epoch 6/10
1000/1000 [==============================] - 1s 754us/step - loss: 11.5038 - acc: 0.1190 - val_loss: 11.5809 - val_acc: 0.0940
Epoch 7/10
1000/1000 [==============================] - 1s 739us/step - loss: 11.5033 - acc: 0.1080 - val_loss: 11.5793 - val_

# RNN 

In [20]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

In [21]:
data_dim = 16
timesteps = 8
num_classes = 10
batch_size = 32

In [23]:
model = Sequential()
model.add(LSTM(32, return_sequences=True, stateful=True,
               batch_input_shape=(batch_size, timesteps, data_dim)))
model.add(LSTM(32, return_sequences=True, stateful=True))
model.add(LSTM(32, stateful=True))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [24]:
X_train = np.random.random((batch_size * 10, timesteps, data_dim))
Y_train = np.random.random((batch_size * 10, num_classes))

In [31]:
X_val = np.random.random((batch_size * 3, timesteps, data_dim))
Y_val = np.random.random((batch_size * 3, num_classes))

In [33]:

model.fit(X_train, Y_train,batch_size=batch_size, epochs=5, shuffle=True,validation_data=(X_val, Y_val))

Train on 320 samples, validate on 96 samples
Epoch 1/5
320/320 [==============================] - 0s 434us/step - loss: 11.3646 - acc: 0.1000 - val_loss: 11.7897 - val_acc: 0.2083
Epoch 2/5
320/320 [==============================] - 0s 512us/step - loss: 11.3634 - acc: 0.0969 - val_loss: 11.7871 - val_acc: 0.1875
Epoch 3/5
320/320 [==============================] - 0s 463us/step - loss: 11.3639 - acc: 0.1031 - val_loss: 11.7901 - val_acc: 0.1458
Epoch 4/5
320/320 [==============================] - 0s 457us/step - loss: 11.3644 - acc: 0.0969 - val_loss: 11.7889 - val_acc: 0.1146
Epoch 5/5
320/320 [==============================] - 0s 502us/step - loss: 11.3638 - acc: 0.1000 - val_loss: 11.7875 - val_acc: 0.1250


In [38]:
# how can i remove the  layer from sequential model
model= Sequential()
model.add(Dense(10, input_dim = 784, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))

print(len(model.layers))
model.pop()
print(len(model.layers))

2
1


In [48]:
# how can i use pre-trained models  in keras
# from keras application we can import 
from keras.applications.xception import Xception
from keras.applications.vgg16 import VGG16
from keras.applications.vgg19 import VGG19
from keras.applications.resnet50 import ResNet50
from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_resnet_v2 import InceptionResNetV2
from keras.applications.mobilenet import MobileNet